### ISSUE TITLE
UnboundLocalError: local variable 'conn' referenced before assignment

### ISSUE THREAD

**Issue by Polytelus** [AttorneyOnlineVidya/tsuserver3#26]
It's been impossible to start the server.

C:\Users\rafael\Desktop\tsuserver3-master>C:\Python35\python start_server.py
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:149: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(cfg)
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:209: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.allowed_iniswaps = yaml.load(iniswaps)
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:162: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.gimp_list = yaml.load(cfg)
C:\Users\rafael\Desktop\tsuserver3-master\server\area_manager.py:190: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  areas = yaml.load(chars)
C:\Users\rafael\Desktop\tsuserver3-master\server\ban_manager.py:74: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.hdid_exempt = yaml.load(hdid)
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:175: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.char_list = yaml.load(chars)
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.music_list = yaml.load(music)
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:204: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.backgrounds = yaml.load(bgs)
C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py:186: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.data = yaml.load(data)
unable to open database file
Traceback (most recent call last):
  File "start_server.py", line 29, in <module>
    main()
  File "start_server.py", line 24, in main
    server = TsuServer3()
  File "C:\Users\rafael\Desktop\tsuserver3-master\server\tsuserver.py", line 68, in __init__
    self.stats_manager = Database(self)
  File "C:\Users\rafael\Desktop\tsuserver3-master\server\database.py", line 14, in __init__
    self.setup_database()
  File "C:\Users\rafael\Desktop\tsuserver3-master\server\database.py", line 26, in setup_database
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

**Comment by Hefaustas** [comment]
I have the same issue

**Comment by oldmud0** [comment]
It looks like the underlying issue is that the `storage/stats` folder does not exist. Creating it should fix that problem.

I don't maintain this repository, but do you just want to run a server? Try https://github.com/AttorneyOnline/tsuserver3.

**Comment by Hefaustas** [comment]
It fixed the issue, thanks for the help. also it turns out I've been using the wrong Tsuserver3 thing...
